# Generated by Django 5.2.12 on 2026-04-08 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="E.g., Computer Science Society", max_length=255
                    ),
                ),
                ("description", models.TextField(help_text="What the club does.")),
                (
                    "contact_email",
                    models.EmailField(help_text="Official club email.", max_length=254),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="A campus administrator must approve the club before they can post events.",
                    ),
                ),
                (
                    "president",
                    models.ForeignKey(
                        help_text="Links to the student who manages the club.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubs_managed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="E.g., Spring Hackathon 2026", max_length=255
                    ),
                ),
                ("description", models.TextField(help_text="Details about the event.")),
                ("date_and_time", models.DateTimeField(help_text="When it happens.")),
                (
                    "location",
                    models.CharField(
                        help_text="Room number or address.", max_length=255
                    ),
                ),
                (
                    "max_capacity",
                    models.IntegerField(
                        help_text="Maximum number of total attendees allowed."
                    ),
                ),
                (
                    "hosting_club",
                    models.ForeignKey(
                        help_text="Which club is throwing this event.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="events.club",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="E.g., General Admission, Early Bird, Free RSVP.",
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Set to 0.00 for free events.",
                        max_digits=6,
                    ),
                ),
                (
                    "quantity_available",
                    models.IntegerField(
                        help_text="E.g., 50 Early Bird tickets available."
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this ticket is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_types",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When they signed up."
                    ),
                ),
                (
                    "has_attended",
                    models.BooleanField(
                        default=False, help_text="Can be checked off at the door."
                    ),
                ),
                (
                    "attendee",
                    models.ForeignKey(
                        help_text="The student who clicked RSVP.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_ticket",
                    models.ForeignKey(
                        help_text="The specific ticket they claimed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.tickettype",
                    ),
                ),
            ],
        ),
    ]
